//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinica
    {
        public Clinica()
        {
            this.Ciudad = new HashSet<Ciudad>();
        }
    
        public string idClinica { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Ciudad> Ciudad { get; set; }
    }
}
